name = "fsys"
version = "1.0.0"
license = "GPL-3.0"
author = "Jason Christopherson"
maintainer = "Jason Christopherson"
copyright = "Copyright 2023-2024, Jason Christopherson"
description = "A Fortran library containing system operations and supporting types."
homepage = "https://github.com/jchristopherson/fsys"

[library]
source-dir = "src"
include-dir = "include"
link = ["stdc++"]

[install]
library = true

[dependencies]
fstring = { git = "https://github.com/jchristopherson/fstring" }

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[[test]]
name = "fsys_test"
source-dir = "test"
main = "fsys_test.f90"