name = "fsys"
version = "1.6.2"
license = "GPL-3.0"
author = "Jason Christopherson"
maintainer = "Jason Christopherson"
copyright = "Copyright 2017-2023, Jason Christopherson"
description = "A Fortran library containing system operations and supporting types."
homepage = "https://github.com/jchristopherson/fsys"

[library]
source-dir = "src"

[install]
library = true

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[[test]]
name = "fsys_test"
source-dir = "test"
main = "fsys_test.f90"